/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddPostDialog: typeof import('./src/components/AddPostDialog.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    ComentarioTile: typeof import('./src/components/ComentarioTile.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    InputText: typeof import('primevue/inputtext')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PostComponent: typeof import('./src/components/PostComponent.vue')['default']
    PostComponentHome: typeof import('./src/components/PostComponentHome.vue')['default']
    QwOla: typeof import('./src/components/qwOla.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('primevue/skeleton')['default']
    Toast: typeof import('primevue/toast')['default']
    UserTile: typeof import('./src/components/UserTile.vue')['default']
  }
}
